all:
	sudo swiftc main.swift\
		EKLinuxDataClasses.swift\
		../../EngineKit/EngineKitCore/EKVector3.swift \
		../../EngineKit/EngineKitCore/EKVector4.swift \
		../../EngineKit/EngineKitCore/EKMatrix.swift \
		../../EngineKit/EngineKitCore/EKVector2.swift \
		../../EngineKit/EngineKitCore/EKSwiftExtensions.swift \
		../../EngineKit/EngineKitCore/EKFileManager.swift \
		../../EngineKit/EngineKitCore/EKOSFactory.swift \
		../../EngineKit/EngineKitCore/EKLanguageEngine.swift \
		../../EngineKit/EngineKitCore/EKEngine.swift \
		../../EngineKit/EngineKitCore/EKEvent.swift \
		../../EngineKit/EngineKitCore/EKColor.swift \
		../../EngineKit/EngineKitCore/EKAddon.swift